include ~/.config/kitty/themes/farout.conf

font_family "JetBrainsMono Nerd Font"
font_size 20.0

map cmd+dot change_font_size all +2.0
map cmd+minus change_font_size all -2.0
map cmd+comma change_font_size all 0

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

