include $HOME/.config/kitty/themes/farout.conf
font_family JetBrainsMono Nerd Font
font_size 18.0


map cmd+dot change_font_size all +2.0
map cmd+minus change_font_size all -2.0
map cmd+comma change_font_size all 0.0

map cmd+t new_tab_with_cwd

