include ./farout.conf


font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 18.0

map cmd+dot change_font_size all +2.0 
map cmd+comma change_font_size all -2.0 
map cmd+minus change_font_size all 0.0 

cursor_shape block


